server:
  port: 8080
spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    url: jdbc:mariadb://192.168.7.100:3306/account_db
    username: root
    password: P@ssw0rd
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      max-lifetime: 300000
