server:
  port: 8080
  servlet:
    context-path: /account-service
spring:
  application:
    name: account-service
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    url: jdbc:mysql://192.168.7.100:3306/account_db
    username: root
    password: P@ssw0rd
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      max-lifetime: 300000
logging:
  level:
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX}|1|%level|${spring.application.name:-}|%X{traceId},%X{spanId},%X{X-Correlation-Id}|${PID:-}|%thread|%logger{40}|%message%n"