services:
  jaeger:
    image: jaegertracing/jaeger
    ports:
      - "26686:16686"
      - "24317:4317"
      - "24318:4318"
      - "25778:5778"
      - "29411:9411"
      - "18889:8889"
    volumes:
      - ./config-spm.yml:/etc/jaeger/config.yml
    command: ["--config", "/etc/jaeger/config.yml"]
  prometheus:
    image: prom/prometheus
    ports:
      - "19090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  mariadb:
    image: mariadb:11
    ports:
      - "3306:3306"
    volumes:
      - "./data-1:/var/lib/mysql"
    environment:
      - MARIADB_USER=admin
      - MARIADB_PASSWORD=P@ssw0rd
      - MARIADB_DATABASE=account_db
      - MARIADB_ROOT_PASSWORD=P@ssw0rd
  redis:
    image: redis:7
    ports:
      - "6379:6379"
